// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';
import {downloader} from '../models';
import {updater} from '../models';
import {config} from '../models';
import {tools} from '../models';
import {queue} from '../models';
import {mediaconv} from '../models';
import {imageconv} from '../models';

export function AddPaths(arg1:string,arg2:Array<string>):Promise<Array<main.FileItem>>;

export function AnalyzeLink(arg1:string):Promise<downloader.Collection>;

export function CancelKind(arg1:string):Promise<void>;

export function CancelTask(arg1:string):Promise<void>;

export function CheckUpdate():Promise<updater.Info>;

export function CollectionDir(arg1:string):Promise<string>;

export function DetectLinks(arg1:string):Promise<Array<downloader.Link>>;

export function ForgetCollection(arg1:string):Promise<void>;

export function ForgetTasks(arg1:Array<string>):Promise<void>;

export function GetCapabilities():Promise<main.Capabilities>;

export function GetDefaultDirs():Promise<Record<string, string>>;

export function GetSettings():Promise<config.Settings>;

export function GetTools():Promise<Array<tools.Status>>;

export function GetVersion():Promise<string>;

export function InstallTool(arg1:string):Promise<void>;

export function InstallUpdate():Promise<void>;

export function ListTasks():Promise<Array<queue.Info>>;

export function OpenFolder(arg1:string):Promise<void>;

export function OutputFolder(arg1:string):Promise<string>;

export function PickDirectory(arg1:string,arg2:string):Promise<string>;

export function PickFiles(arg1:string):Promise<Array<main.FileItem>>;

export function PickFolder(arg1:string):Promise<Array<main.FileItem>>;

export function PickToolPath(arg1:string):Promise<void>;

export function RecheckTools():Promise<Array<tools.Status>>;

export function ResetToolPath(arg1:string):Promise<void>;

export function RevealFile(arg1:string):Promise<void>;

export function SaveSettings(arg1:config.Settings):Promise<config.Settings>;

export function StartAudio(arg1:Array<main.JobItem>,arg2:mediaconv.AudioOptions):Promise<Array<main.JobRef>>;

export function StartDownloads(arg1:string,arg2:Array<string>,arg3:downloader.Options):Promise<Array<main.JobRef>>;

export function StartImage(arg1:Array<main.JobItem>,arg2:imageconv.Options):Promise<Array<main.JobRef>>;

export function StartVideo(arg1:Array<main.JobItem>,arg2:main.VideoJob):Promise<Array<main.JobRef>>;
