// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddPaths(arg1, arg2) {
  return window['go']['main']['App']['AddPaths'](arg1, arg2);
}

export function AnalyzeLink(arg1) {
  return window['go']['main']['App']['AnalyzeLink'](arg1);
}

export function CancelAfterQueue() {
  return window['go']['main']['App']['CancelAfterQueue']();
}

export function CancelKind(arg1) {
  return window['go']['main']['App']['CancelKind'](arg1);
}

export function CancelTask(arg1) {
  return window['go']['main']['App']['CancelTask'](arg1);
}

export function CertInfo(arg1, arg2) {
  return window['go']['main']['App']['CertInfo'](arg1, arg2);
}

export function CheckUpdate() {
  return window['go']['main']['App']['CheckUpdate']();
}

export function ClearHistory() {
  return window['go']['main']['App']['ClearHistory']();
}

export function CollectionDir(arg1) {
  return window['go']['main']['App']['CollectionDir'](arg1);
}

export function CreateCertificate(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['CreateCertificate'](arg1, arg2, arg3, arg4, arg5);
}

export function DataFolder() {
  return window['go']['main']['App']['DataFolder']();
}

export function DetectLinks(arg1) {
  return window['go']['main']['App']['DetectLinks'](arg1);
}

export function ForgetCollection(arg1) {
  return window['go']['main']['App']['ForgetCollection'](arg1);
}

export function ForgetTasks(arg1) {
  return window['go']['main']['App']['ForgetTasks'](arg1);
}

export function GetAfterQueue() {
  return window['go']['main']['App']['GetAfterQueue']();
}

export function GetCapabilities() {
  return window['go']['main']['App']['GetCapabilities']();
}

export function GetDefaultDirs() {
  return window['go']['main']['App']['GetDefaultDirs']();
}

export function GetHWEncoders() {
  return window['go']['main']['App']['GetHWEncoders']();
}

export function GetHistory() {
  return window['go']['main']['App']['GetHistory']();
}

export function GetSendTo() {
  return window['go']['main']['App']['GetSendTo']();
}

export function GetSettings() {
  return window['go']['main']['App']['GetSettings']();
}

export function GetTools() {
  return window['go']['main']['App']['GetTools']();
}

export function GetVersion() {
  return window['go']['main']['App']['GetVersion']();
}

export function InstallTool(arg1) {
  return window['go']['main']['App']['InstallTool'](arg1);
}

export function InstallUpdate() {
  return window['go']['main']['App']['InstallUpdate']();
}

export function ListTasks() {
  return window['go']['main']['App']['ListTasks']();
}

export function OpenFileDefault(arg1) {
  return window['go']['main']['App']['OpenFileDefault'](arg1);
}

export function OpenFolder(arg1) {
  return window['go']['main']['App']['OpenFolder'](arg1);
}

export function OutputFolder(arg1) {
  return window['go']['main']['App']['OutputFolder'](arg1);
}

export function PathExists(arg1) {
  return window['go']['main']['App']['PathExists'](arg1);
}

export function PdfCompare(arg1, arg2) {
  return window['go']['main']['App']['PdfCompare'](arg1, arg2);
}

export function PdfDoc(arg1, arg2) {
  return window['go']['main']['App']['PdfDoc'](arg1, arg2);
}

export function PdfEnvironment() {
  return window['go']['main']['App']['PdfEnvironment']();
}

export function PdfFind(arg1, arg2, arg3) {
  return window['go']['main']['App']['PdfFind'](arg1, arg2, arg3);
}

export function PdfOcrLanguages() {
  return window['go']['main']['App']['PdfOcrLanguages']();
}

export function PdfSaveCapture(arg1) {
  return window['go']['main']['App']['PdfSaveCapture'](arg1);
}

export function PdfScan() {
  return window['go']['main']['App']['PdfScan']();
}

export function PdfWarmup() {
  return window['go']['main']['App']['PdfWarmup']();
}

export function PickDirectory(arg1, arg2) {
  return window['go']['main']['App']['PickDirectory'](arg1, arg2);
}

export function PickFile(arg1, arg2, arg3) {
  return window['go']['main']['App']['PickFile'](arg1, arg2, arg3);
}

export function PickFiles(arg1) {
  return window['go']['main']['App']['PickFiles'](arg1);
}

export function PickFolder(arg1) {
  return window['go']['main']['App']['PickFolder'](arg1);
}

export function PickToolPath(arg1) {
  return window['go']['main']['App']['PickToolPath'](arg1);
}

export function RecheckTools() {
  return window['go']['main']['App']['RecheckTools']();
}

export function RemoveHistory(arg1) {
  return window['go']['main']['App']['RemoveHistory'](arg1);
}

export function ResetToolPath(arg1) {
  return window['go']['main']['App']['ResetToolPath'](arg1);
}

export function RevealFile(arg1) {
  return window['go']['main']['App']['RevealFile'](arg1);
}

export function RoutePaths(arg1) {
  return window['go']['main']['App']['RoutePaths'](arg1);
}

export function SaveSettings(arg1) {
  return window['go']['main']['App']['SaveSettings'](arg1);
}

export function SetAfterQueue(arg1) {
  return window['go']['main']['App']['SetAfterQueue'](arg1);
}

export function SetEntrySource(arg1, arg2, arg3) {
  return window['go']['main']['App']['SetEntrySource'](arg1, arg2, arg3);
}

export function SetSendTo(arg1) {
  return window['go']['main']['App']['SetSendTo'](arg1);
}

export function StartAudio(arg1, arg2) {
  return window['go']['main']['App']['StartAudio'](arg1, arg2);
}

export function StartDownloads(arg1, arg2, arg3) {
  return window['go']['main']['App']['StartDownloads'](arg1, arg2, arg3);
}

export function StartImage(arg1, arg2) {
  return window['go']['main']['App']['StartImage'](arg1, arg2);
}

export function StartPdf(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['StartPdf'](arg1, arg2, arg3, arg4);
}

export function StartPdfCombine(arg1, arg2, arg3) {
  return window['go']['main']['App']['StartPdfCombine'](arg1, arg2, arg3);
}

export function StartPdfEdit(arg1) {
  return window['go']['main']['App']['StartPdfEdit'](arg1);
}

export function StartVideo(arg1, arg2) {
  return window['go']['main']['App']['StartVideo'](arg1, arg2);
}

export function TakeLaunchFiles() {
  return window['go']['main']['App']['TakeLaunchFiles']();
}
