// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddPaths(arg1, arg2) {
  return window['go']['main']['App']['AddPaths'](arg1, arg2);
}

export function AddSubscription(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['AddSubscription'](arg1, arg2, arg3, arg4, arg5);
}

export function AnalyzeLink(arg1) {
  return window['go']['main']['App']['AnalyzeLink'](arg1);
}

export function CancelAfterQueue() {
  return window['go']['main']['App']['CancelAfterQueue']();
}

export function CancelKind(arg1) {
  return window['go']['main']['App']['CancelKind'](arg1);
}

export function CancelModel(arg1, arg2) {
  return window['go']['main']['App']['CancelModel'](arg1, arg2);
}

export function CancelTask(arg1) {
  return window['go']['main']['App']['CancelTask'](arg1);
}

export function CertInfo(arg1, arg2) {
  return window['go']['main']['App']['CertInfo'](arg1, arg2);
}

export function CheckSubscription(arg1) {
  return window['go']['main']['App']['CheckSubscription'](arg1);
}

export function CheckUpdate() {
  return window['go']['main']['App']['CheckUpdate']();
}

export function ClearHistory() {
  return window['go']['main']['App']['ClearHistory']();
}

export function CloseWindow() {
  return window['go']['main']['App']['CloseWindow']();
}

export function CollectionDir(arg1) {
  return window['go']['main']['App']['CollectionDir'](arg1);
}

export function CreateCertificate(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['CreateCertificate'](arg1, arg2, arg3, arg4, arg5);
}

export function DataFolder() {
  return window['go']['main']['App']['DataFolder']();
}

export function DeleteModel(arg1, arg2) {
  return window['go']['main']['App']['DeleteModel'](arg1, arg2);
}

export function DetectLinks(arg1) {
  return window['go']['main']['App']['DetectLinks'](arg1);
}

export function DiscardPendingDownloads() {
  return window['go']['main']['App']['DiscardPendingDownloads']();
}

export function ExportSettings(arg1) {
  return window['go']['main']['App']['ExportSettings'](arg1);
}

export function ForgetCollection(arg1) {
  return window['go']['main']['App']['ForgetCollection'](arg1);
}

export function ForgetTasks(arg1) {
  return window['go']['main']['App']['ForgetTasks'](arg1);
}

export function GetAfterQueue() {
  return window['go']['main']['App']['GetAfterQueue']();
}

export function GetAutostart() {
  return window['go']['main']['App']['GetAutostart']();
}

export function GetCLICommand() {
  return window['go']['main']['App']['GetCLICommand']();
}

export function GetCapabilities() {
  return window['go']['main']['App']['GetCapabilities']();
}

export function GetDefaultDirs() {
  return window['go']['main']['App']['GetDefaultDirs']();
}

export function GetHWEncoders() {
  return window['go']['main']['App']['GetHWEncoders']();
}

export function GetHistory() {
  return window['go']['main']['App']['GetHistory']();
}

export function GetLinkProtocol() {
  return window['go']['main']['App']['GetLinkProtocol']();
}

export function GetSendTo() {
  return window['go']['main']['App']['GetSendTo']();
}

export function GetSettings() {
  return window['go']['main']['App']['GetSettings']();
}

export function GetTools() {
  return window['go']['main']['App']['GetTools']();
}

export function GetVersion() {
  return window['go']['main']['App']['GetVersion']();
}

export function ImportSettings() {
  return window['go']['main']['App']['ImportSettings']();
}

export function InstallModel(arg1, arg2) {
  return window['go']['main']['App']['InstallModel'](arg1, arg2);
}

export function InstallTool(arg1) {
  return window['go']['main']['App']['InstallTool'](arg1);
}

export function InstallUpdate() {
  return window['go']['main']['App']['InstallUpdate']();
}

export function ListModels(arg1) {
  return window['go']['main']['App']['ListModels'](arg1);
}

export function ListSubscriptions() {
  return window['go']['main']['App']['ListSubscriptions']();
}

export function ListTasks() {
  return window['go']['main']['App']['ListTasks']();
}

export function OpenFileDefault(arg1) {
  return window['go']['main']['App']['OpenFileDefault'](arg1);
}

export function OpenFolder(arg1) {
  return window['go']['main']['App']['OpenFolder'](arg1);
}

export function OutputFolder(arg1) {
  return window['go']['main']['App']['OutputFolder'](arg1);
}

export function PathExists(arg1) {
  return window['go']['main']['App']['PathExists'](arg1);
}

export function PdfCompare(arg1, arg2) {
  return window['go']['main']['App']['PdfCompare'](arg1, arg2);
}

export function PdfDetails(arg1, arg2) {
  return window['go']['main']['App']['PdfDetails'](arg1, arg2);
}

export function PdfDoc(arg1, arg2) {
  return window['go']['main']['App']['PdfDoc'](arg1, arg2);
}

export function PdfEnvironment() {
  return window['go']['main']['App']['PdfEnvironment']();
}

export function PdfFind(arg1, arg2, arg3) {
  return window['go']['main']['App']['PdfFind'](arg1, arg2, arg3);
}

export function PdfFormFields(arg1, arg2) {
  return window['go']['main']['App']['PdfFormFields'](arg1, arg2);
}

export function PdfOcrLanguages() {
  return window['go']['main']['App']['PdfOcrLanguages']();
}

export function PdfSaveCapture(arg1) {
  return window['go']['main']['App']['PdfSaveCapture'](arg1);
}

export function PdfScan() {
  return window['go']['main']['App']['PdfScan']();
}

export function PdfTSAServers() {
  return window['go']['main']['App']['PdfTSAServers']();
}

export function PdfWarmup() {
  return window['go']['main']['App']['PdfWarmup']();
}

export function PendingDownloads() {
  return window['go']['main']['App']['PendingDownloads']();
}

export function PickDirectory(arg1, arg2) {
  return window['go']['main']['App']['PickDirectory'](arg1, arg2);
}

export function PickFile(arg1, arg2, arg3) {
  return window['go']['main']['App']['PickFile'](arg1, arg2, arg3);
}

export function PickFiles(arg1) {
  return window['go']['main']['App']['PickFiles'](arg1);
}

export function PickFolder(arg1) {
  return window['go']['main']['App']['PickFolder'](arg1);
}

export function PickToolPath(arg1) {
  return window['go']['main']['App']['PickToolPath'](arg1);
}

export function QuitApp() {
  return window['go']['main']['App']['QuitApp']();
}

export function RecheckTools() {
  return window['go']['main']['App']['RecheckTools']();
}

export function RemoveHistory(arg1) {
  return window['go']['main']['App']['RemoveHistory'](arg1);
}

export function RemoveSubscription(arg1) {
  return window['go']['main']['App']['RemoveSubscription'](arg1);
}

export function ResetToolPath(arg1) {
  return window['go']['main']['App']['ResetToolPath'](arg1);
}

export function ResumePendingDownloads() {
  return window['go']['main']['App']['ResumePendingDownloads']();
}

export function RevealFile(arg1) {
  return window['go']['main']['App']['RevealFile'](arg1);
}

export function RoutePaths(arg1) {
  return window['go']['main']['App']['RoutePaths'](arg1);
}

export function RunWorkflow(arg1, arg2) {
  return window['go']['main']['App']['RunWorkflow'](arg1, arg2);
}

export function SaveSettings(arg1) {
  return window['go']['main']['App']['SaveSettings'](arg1);
}

export function SetAfterQueue(arg1) {
  return window['go']['main']['App']['SetAfterQueue'](arg1);
}

export function SetAutostart(arg1) {
  return window['go']['main']['App']['SetAutostart'](arg1);
}

export function SetCLICommand(arg1) {
  return window['go']['main']['App']['SetCLICommand'](arg1);
}

export function SetEntrySource(arg1, arg2, arg3) {
  return window['go']['main']['App']['SetEntrySource'](arg1, arg2, arg3);
}

export function SetLinkProtocol(arg1) {
  return window['go']['main']['App']['SetLinkProtocol'](arg1);
}

export function SetSendTo(arg1) {
  return window['go']['main']['App']['SetSendTo'](arg1);
}

export function SetSubscription(arg1, arg2, arg3) {
  return window['go']['main']['App']['SetSubscription'](arg1, arg2, arg3);
}

export function StartAudio(arg1, arg2) {
  return window['go']['main']['App']['StartAudio'](arg1, arg2);
}

export function StartCollage(arg1, arg2) {
  return window['go']['main']['App']['StartCollage'](arg1, arg2);
}

export function StartDownloads(arg1, arg2, arg3) {
  return window['go']['main']['App']['StartDownloads'](arg1, arg2, arg3);
}

export function StartImage(arg1, arg2) {
  return window['go']['main']['App']['StartImage'](arg1, arg2);
}

export function StartPdf(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['StartPdf'](arg1, arg2, arg3, arg4);
}

export function StartPdfCombine(arg1, arg2, arg3) {
  return window['go']['main']['App']['StartPdfCombine'](arg1, arg2, arg3);
}

export function StartPdfEdit(arg1) {
  return window['go']['main']['App']['StartPdfEdit'](arg1);
}

export function StartPdfForm(arg1, arg2, arg3) {
  return window['go']['main']['App']['StartPdfForm'](arg1, arg2, arg3);
}

export function StartPdfMeta(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['StartPdfMeta'](arg1, arg2, arg3, arg4);
}

export function StartSlideshow(arg1, arg2) {
  return window['go']['main']['App']['StartSlideshow'](arg1, arg2);
}

export function StartSubtitle(arg1, arg2) {
  return window['go']['main']['App']['StartSubtitle'](arg1, arg2);
}

export function StartVideo(arg1, arg2) {
  return window['go']['main']['App']['StartVideo'](arg1, arg2);
}

export function SubtitleLanguages() {
  return window['go']['main']['App']['SubtitleLanguages']();
}

export function SyncRecipes(arg1) {
  return window['go']['main']['App']['SyncRecipes'](arg1);
}

export function TakeLaunchFiles() {
  return window['go']['main']['App']['TakeLaunchFiles']();
}

export function TakeLaunchLinks() {
  return window['go']['main']['App']['TakeLaunchLinks']();
}

export function ToolsDetected() {
  return window['go']['main']['App']['ToolsDetected']();
}
